In [3]:
import numpy as np
import matplotlib.pyplot as pp

In [5]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [6]:
a.dtype

dtype('int32')

In [8]:
a = np.array([1,2,3,4,5], dtype=np.float64)
a

array([1., 2., 3., 4., 5.])

In [9]:
a.ndim, a.shape, a.size

(1, (5,), 5)

In [11]:
b = np.array([[1,2,3,4,5], [6,7,8,9,10]], dtype=np.float64)
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [13]:
b.dtype

dtype('float64')

In [14]:
b.ndim, b.shape, b.size

(2, (2, 5), 10)

In [15]:
np.zeros((3,3),'d')

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.empty((4,4),'d')

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        8.45593934e-307],
       [1.24610994e-306, 4.45057637e-308, 1.95821982e-306,
        1.37961641e-306],
       [7.56599807e-307, 8.90104239e-307, 1.24610383e-306,
        7.56587584e-307],
       [8.45602762e-307, 1.51317517e-306, 9.34610469e-307,
        2.22522596e-306]])

In [20]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [22]:
np.random.standard_normal((2,4))

array([[-0.64302778, -1.06500652,  0.82995512, -0.27290208],
       [-0.99342565,  0.28496627,  0.80709812,  1.35963881]])

In [23]:
a = np.random.standard_normal((2,3))
b = np.random.standard_normal((2,3))

np.vstack([a,b])

array([[ 0.97450896,  0.68316098,  0.36600178],
       [ 1.02469204,  0.3287368 , -0.56337124],
       [ 0.75927181, -0.52548563, -1.9279735 ],
       [-0.40845218,  0.44502814,  0.96805218]])

In [24]:
a.transpose()

array([[ 0.97450896,  1.02469204],
       [ 0.68316098,  0.3287368 ],
       [ 0.36600178, -0.56337124]])

In [25]:
np.save('example.npy',a)

In [26]:
al = np.load('example.npy')

In [27]:
al

array([[ 0.97450896,  0.68316098,  0.36600178],
       [ 1.02469204,  0.3287368 , -0.56337124]])