In [1]:
import numpy as np

In [3]:
v = np.linspace(0,10,5)

In [4]:
v[0]

0.0

In [5]:
v[1]

2.5

In [6]:
v[-1]

10.0

In [9]:
vv = np.random.random((5,4))
vv

array([[0.26918759, 0.76459138, 0.11647263, 0.08107242],
       [0.39625184, 0.01611933, 0.83688059, 0.29874343],
       [0.44173022, 0.43589542, 0.85550097, 0.49330099],
       [0.97042778, 0.87246472, 0.25470868, 0.49796353],
       [0.49614582, 0.98573036, 0.07389008, 0.48173429]])

In [10]:
vv[0,0]

0.26918758663086295

In [11]:
vv[4,3]

0.48173428900299187

In [14]:
ll = [[1,2,3],[4,5,6],[7,8,9]]

In [16]:
ll[1][2]

6

In [17]:
v[2:4]

array([5. , 7.5])

In [18]:
vv[2:5,1]

array([0.43589542, 0.87246472, 0.98573036])

In [19]:
vv[2:5,1:2]

array([[0.43589542],
       [0.87246472],
       [0.98573036]])

In [20]:
vv[2:-1,:]

array([[0.44173022, 0.43589542, 0.85550097, 0.49330099],
       [0.97042778, 0.87246472, 0.25470868, 0.49796353]])

In [21]:
vv[:,::2]

array([[0.26918759, 0.11647263],
       [0.39625184, 0.83688059],
       [0.44173022, 0.85550097],
       [0.97042778, 0.25470868],
       [0.49614582, 0.07389008]])

In [22]:
v2 = v[2:4]

In [23]:
v2[0] = 0

In [24]:
v

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

In [25]:
v3 = v[2:4].copy()

In [26]:
v

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

In [27]:
v[[1,2,3]]

array([2.5, 0. , 7.5])

In [32]:
bool_index = v > 0

In [33]:
v[bool_index]

array([ 2.5,  7.5, 10. ])

In [36]:
vv[vv > 0.5] = vv[vv > 0.5] * 2

In [37]:
vv

array([[0.26918759, 1.52918277, 0.11647263, 0.08107242],
       [0.39625184, 0.01611933, 1.67376117, 0.29874343],
       [0.44173022, 0.43589542, 1.71100195, 0.49330099],
       [1.94085555, 1.74492943, 0.25470868, 0.49796353],
       [0.49614582, 1.97146071, 0.07389008, 0.48173429]])